### ISSUE TITLE
No Tax calculated on multiple quantities - only on single items

### ISSUE THREAD

**Issue by in8dna** [openstore-ecommerce/OpenStore#142]
I can demonstrate the issue with access if you like. What is happening is that customers are purchasing multiple quantities of items but only being charged tax for a single (1) item. Tax on quantity (2) of an item is 1/2 what it should be. Tax on the quantity of (3) is 1/3 of what it should be.

Version 4.14 on DNN 9.8

![BacFlo-tax-calculation-error](https://user-images.githubusercontent.com/13932030/113804931-17929a80-9725-11eb-8ca2-22b239960f78.jpg)

**Comment by leedavi** [comment]
OK  this is the code...
--------------

            var appliedcost = cartItemInfo.GetXmlPropertyDouble("genxml/appliedcost");
            // check if dealer and if dealertotal cost exists. ()
            if (cartItemInfo.GetXmlPropertyBool("genxml/isdealer")) appliedcost = cartItemInfo.GetXmlPropertyDouble("genxml/dealercost");

            var taxrate = GetTaxRate(cartItemInfo, rateDic);

            taxtotal = AddTaxCost(taxtotal, appliedcost, taxrate);

            return Math.Round(taxtotal, 2);

-------------

The "genxml/appliedcost" is the subtotal before tax of all the products and quantities.  So this looks correct.

I think this may be a template issue, where it is using the wrong token. 

What template are you using?

On the email...

I think this....
```
  <td colspan="2" class="text-right removecolumn">@ResourceKey("General.Tax")</td>
  <td class="text-right">@CurrencyOf(@nbi.GetXmlPropertyDouble("genxml/taxcost"))</td>
```
should be ...
```
  <td colspan="2" class="text-right removecolumn">@ResourceKey("General.Tax")</td>
  <td class="text-right">@CurrencyOf(@nbi.GetXmlPropertyDouble("genxml/appliedtax"))</td>
```

What amount is going to the bank ??

This code has not changed for 5 or 6 years.  I find it difficult to believe it's been wrong all that time.  But, maybe another fix has had done something, it's not impossible.  We need to find out what.   I'll have a look today for a solution.

Thx for reporting it.

**Comment by leedavi** [comment]
You are using the default tax provider, right ?

**Comment by leedavi** [comment]
I gone through a few options with tax and it looks OK..

![image](https://user-images.githubusercontent.com/5583141/113819457-a0d3bc80-9779-11eb-8378-d6288b79a298.png)

What templates are you using, maybe we need to adjust them.  The suggestion I made above, with the templates didn't work.  Obviously because it looks to be calculating correctly.

I still have seen this on one of our sites, I think it's only a display issue and just needs to be adjusted in the templates.

**Comment by leedavi** [comment]
Good catch.  The problem was an error is you have multiple quantities when tax is not included in the price.

All our clients has it included, and I can't remember seeing a store that was not included.  But it was an issue, even if the bank amount was correct in the included tax stores..

Here is the fix,

https://github.com/openstore-ecommerce/OpenStore/releases/tag/v4.1.5

I'm running v4.1.5 on our latest store and I was going to make it stable.   Give it a test and let me know.

Thank you for pointing it out.

**Comment by in8dna** [comment]
Perfect - thank you, the client is pleased to collect the correct amount of tax!

I agree that the US practice of adding tax AFTER showing the sales amount is a little... misleading, but that's what everyone expects.

**Comment by in8dna** [comment]
1.	Thanks for the tax calculator patch. That helps a lot.
 
2.	We need to pay you for the Stripe Plugin. Please send a link for the $400.
 
3.	Don is asking how it is going on the Stripe Plugin for the v3 store. He’s sold his home and needs to decide if he moves the inventory from Washington State to Arizona, or if he disposes of all of it. If the plugin will work in the v3 store, he’ll move the inventory.
 
If it cannot work in the v3 store, he doesn’t have enough years to move the inventory data into v4 and to rebuild 23 websites (https://donsautoparts.com/car-parts-garages  <https://donsautoparts.com/car-parts-garages%20> )
 
So… no pressure. He’s looking to your magic to decide what he does with all his parts.
 
Thanks again.
 
Daniel

**Comment by leedavi** [comment]
Hi, unfortunately I have not had any time to look at the v3 version.

The problem is that the payment provider works, slightly different.

However, you know that the v3 Database is nearly identical to the v4,  You can export form v3 and import into v4

Have a read of this and see what you think.

https://github.com/openstore-ecommerce/OpenStore/blob/master/Installation/Readme_NBS_Upgrade.txt

I have moved 1 or 2 sites with method 2.  It does work.

**Comment by in8dna** [comment]
Ok, thanks. I’ll discuss moving with option 2 and see how he feels about a couple weeks of down-time across all his sites.
 
Thanks

**Comment by leedavi** [comment]
I would try Method 2 as my first approach.  Try it on a test system and see if it all works.   If it does, you'll be able to say only 1 Day downtime.  Probably less, if you understand what you need to do before you jump on it.
