### ISSUE TITLE
The + character is being exclude from product titles

### ISSUE THREAD

**Issue by Rodien** [openstore-ecommerce/OpenStore#74]
I'm trying to save a product with the (+) character right after the product title but when I click on save the (+) character gets remove. 

I can save product titles with these symbols %@#$^*( )=-_![]{} without a problem. 

The only symbol  that gets remove is the (+) symbol.

I'm using NBrightTemplateSys 8.5.1 and modules are version 4..1.1.

**Comment by leedavi** [comment]
I "think" this is on purpose, because the system strips any invalid chars for the friendly name in the url.  The product name is used in the url, I suppose it should only remove when creating the url, but maybe it strips on save, for some reason,

You could try and turn off friendly urls and see if it saves it, but it may not.

**Comment by Rodien** [comment]
If this is the case then the product name should generate a slug and the slug should be use as URL. 

p.s Thanks for the quick response.

**Comment by Rodien** [comment]
It's probably something else going on. 

Because why is it allowing me to save these chars %@#$^*( )=-_![]{} but not + 

I'm looking into it maybe I'll find what the problem is.

**Comment by leedavi** [comment]
Good Point, let me know if you find anything.

**Comment by leedavi** [comment]
I notice it's the same for all fields on the product.  The JavaScript that transmits the data from the page to the API is 6+ years old.  It works by taking all the input fields, building an XML and posting to the API.  I wonder if there was some issue (I can't remember one) with building the XML data document or posting it.  But maybe making it complaint for the post removed the character.

I've just tested the new version of this JS and it uses JSON instead of XML for the transfer, and that works with + sign.  Unfortunately, OpenStore is stuck with this version.   

But continue to see if you can find a reason why, if it's a c# issue we "might" be able to get a solution.  But if the + sign has been removed, it will be for a reason, so I'm a little concerned about braking something else.

**Comment by Rodien** [comment]
An update on what I have found. 

**Page**: Admin_ProductDetail.cshtml 

@{
    var info = (NBrightInfo)Model.List.First();
    var prdData = new ProductData(info.ItemID, info.PortalId, info.Lang);
}



**General Area:**
@TextBox(info, "genxml/lang/genxml/textbox/txtproductname", "class='form-control' maxlength='250'")


**Modellen Area**:
@ResourceKey("General.Code")</label>@TextBox(nbiModel, "genxml/textbox/txtmodelref_" + lp1, "class='form-control input-sm' maxlength='250' ", "")


**Extra**:
@TextBox(nbiModel, "genxml/lang/genxml/textbox/txtextra_" + lp1, "class='form-control input-sm' maxlength='250'  ")


When using the info variable the + symbol gets remove. 

When using the prdData.Models + symbol doesn't get remove. 



So every data field that uses the info variable doesn't accept the + symbol.

But fields that uses the  prdData variable does accept the + symbol.

**Comment by trouble2** [comment]
So....now what?
We have a customer who would really like to have products with a '+' in the name.

**Comment by Rodien** [comment]
The client went ahead and used "Plus" in place of (+). So, I never end up looking further into this issue.

**Comment by leedavi** [comment]
I'm doing some work on OpenStore for a client, so I put a trace on where the + disappeared.

It's Line 2782 of NBrightBuyUtils.cs

            var strIn = HttpUtility.UrlDecode(Utils.RequestParam(context, "inputxml"));

This is decoding the request from from the Ajax post.  The models work because then are encoded into ASCII decimal code before being posted.  

Ideally we could do that with all post data or transmit in JSON with simplisityJS,  https://www.simplisityjs.org/  Changing OpenStore for this would be a major upgrade in testing for  the Ajax JS.  And only small bonus, I doubt it will ever be done.   The JS being used is old and tested, It's not something to change in an open source project, unless things are seriously broken.
