### ISSUE TITLE
Mini Cart Displays Wrong Total

### ISSUE THREAD

**Issue by seekthelight** [openstore-ecommerce/OpenStore#81]
![Screenshot_2020-03-03 Screen Printing Prints](https://user-images.githubusercontent.com/15399177/75846852-22049700-5da3-11ea-94a8-5f3f83d34906.png)

**Comment by seekthelight** [comment]
![Screenshot_2020-03-03 mi1Printing Services by mi1Printing Services Limited - Shopping Cart](https://user-images.githubusercontent.com/15399177/75846857-2761e180-5da3-11ea-8609-fbfcdfbb2642.png)

**Comment by seekthelight** [comment]
The first shot is the basket and the second shot is what was actually in the cart.

**Comment by leedavi** [comment]
If you change the qty back to 1, does it work and go back to 1??

This could be a template of JS error adding 1200.  Could it be decimal point being translated different in different languages??

**Comment by seekthelight** [comment]
Items in the main cart is no issue. Just the calculation on the mini cart.

**Comment by leedavi** [comment]
OK, sorry I see now.   
Can you repeat this incorrect calculation with other products?
What version of DNN is it?
What version of OpenStore is it?

**Comment by leedavi** [comment]
I see, it also does this on the demo.  When the mini-cart is on the full cart page.

I think this is becuase we are not getting an ajax update to the mini-cart when we recalculate the cart.

On the demo is I refresh the page the calculation is correct.

Do you get the same behaviour? 

I think this is a display problem, not a DB or calculation problem.  But I agree it should be fix.  The problem is, although this seem a small change I think it'll involve rewriting some of the cart functionality. 

I'll try and get a fix ASAP.

The work around is to remove the mini-cart from the fullcart page.  Something we usually do anyway.

**Comment by leedavi** [comment]
The ClassicAjax theme has been updated at some point to fix this.
